
import "../../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { WeatherDataProvider } from "@/context/weatherData";



export const metadata = {
  title: "Loons Labs Front End",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <WeatherDataProvider>
            <main>{children}</main>
            <Toaster />
          </WeatherDataProvider>

        </ThemeProvider>
      </body>
    </html>
  );
}
